name: naraakom
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=3.2.0-134.1.beta <4.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.6
  flutter_bloc: ^8.1.3
  dartz:
  carousel_slider: ^4.0.0
  smooth_page_indicator: ^1.0.0+2
  intl: ^0.18.0
  flutter_animate:
  firebase_core: ^2.24.2
  shared_preferences: ^2.2.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  fluttertoast: ^8.2.4
  record: ^5.0.4
  flutter_sound:
  permission_handler:
  file_picker: ^6.1.1
  dio: ^5.4.0
  open_file: ^3.3.2
  photo_view: ^0.14.0
  flutter_local_notifications: ^16.3.1+1
  firebase_messaging: ^14.7.10
  image_picker: ^1.0.7
  record_mp3: ^3.0.0
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Nunito Sans
      fonts: 
        - asset: assets/fonts/NunitoSansRegular.ttf
          weight: 400
        - asset: assets/fonts/NunitoSansSemiBold.ttf
          weight: 600
        - asset: assets/fonts/NunitoSansExtraBold.ttf
          weight: 800
        - asset: assets/fonts/NunitoSansBold.ttf
          weight: 700
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
